{
 "title": "Monitoring 2 Nodes",
 "description": "Docker host metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime node01",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"nodeexporter:9100\"} - node_boot_time_seconds{instance=~\"nodeexporter:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Idle Node01",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\", mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{instance=~\"nodeexporter:9100\", mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores Node01",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=\"cadvisor:8080\"}"
    }
   ]
  },
  {
   "title": "Available Memory Node01",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"nodeexporter:9100\"}"
    }
   ]
  },
  {
   "title": "Free Swap Node01",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"nodeexporter:9100\"}"
    }
   ]
  },
  {
   "title": "Free Storage Node01",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{instance=~\"nodeexporter:9100\"})"
    }
   ]
  },
  {
   "title": "Uptime node02",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"node02.netology.cloud:9100\"} - node_boot_time_seconds{instance=~\"node02.netology.cloud:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Idle Node02",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"node02.netology.cloud:9100\", mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{instance=~\"node02.netology.cloud:9100\", mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores Node01",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=\"cadvisor:8080\"}"
    }
   ]
  },
  {
   "title": "Available Memory Node02",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"node02.netology.cloud:9100\"}"
    }
   ]
  },
  {
   "title": "Free Swap Node02",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"node02.netology.cloud:9100\"}"
    }
   ]
  },
  {
   "title": "Free Storage Node02",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{instance=~\"node02.netology.cloud:9100\"})"
    }
   ]
  },
  {
   "title": "Load Average 1m Node01",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Load Average 1m Node02",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes Node01",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "blocked by I/O"
    }
   ]
  },
  {
   "title": "Processes Node02",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "blocked by I/O"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " irate(node_intr_total[5m])", "legendFormat": "interrupts" }
   ]
  },
  {
   "title": "CPU Usage Node01",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"nodeexporter:9100\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU Usage Node02",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"node02.netology.cloud:9100\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"node02.netology.cloud:9100\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage Node01",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"} - (node_memory_MemFree_bytes{instance=~\"nodeexporter:9100\"} + node_memory_Buffers_bytes{instance=~\"nodeexporter:9100\"} + node_memory_Cached_bytes{instance=~\"nodeexporter:9100\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Memory Usage Node02",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"node02.netology.cloud:9100\"} - (node_memory_MemFree_bytes{instance=~\"node02.netology.cloud:9100\"} + node_memory_Buffers_bytes{instance=~\"node02.netology.cloud:9100\"} + node_memory_Cached_bytes{instance=~\"node02.netology.cloud:9100\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "I/O Usage Node01",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"nodeexporter:9100\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"nodeexporter:9100\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=~\"nodeexporter:9100\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "I/O Usage Node02",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"node02.netology.cloud:9100\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"node02.netology.cloud:9100\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=~\"node02.netology.cloud:9100\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Swap Usage Node01",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"nodeexporter:9100\"} - node_memory_SwapFree_bytes{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O Node01",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=~\"nodeexporter:9100\"}[1m]) * 4096 or irate(node_vmstat_pswpin{instance=~\"nodeexporter:9100\"}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=~\"nodeexporter:9100\"}[1m]) * 4096 or irate(node_vmstat_pswpout{instance=~\"nodeexporter:9100\"}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Swap Usage Node02",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"node02.netology.cloud:9100\"} - node_memory_SwapFree_bytes{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"node02.netology.cloud:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O Node02",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=~\"node02.netology.cloud:9100\"}[1m]) * 4096 or irate(node_vmstat_pswpin{instance=~\"node02.netology.cloud:9100\"}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=~\"node02.netology.cloud:9100\"}[1m]) * 4096 or irate(node_vmstat_pswpout{instance=~\"node02.netology.cloud:9100\"}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network Usage Node01",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\", instance=~\"nodeexporter:9100\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\", instance=~\"nodeexporter:9100\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Network Usage Node02",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\", instance=~\"node02.netology.cloud:9100\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\", instance=~\"node02.netology.cloud:9100\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  }
 ]
}